from typing import List

DEFAULT_PROPERTIES:List[str] = [
    "No JavaScript",
    "Is Deployable",
    "Related to Microsoft Products",
    "Uses IPFS",
    "Uses CDN",
    "",
    "",
    "Redirection with window.location.href",
    "Redirection with window.open()",
    "Redirection with navigation.navigate()",
    "Redirection with window.location.replace()",
    "Redirection with window.location.replace()",
    "Redirection with window.location.assign()",
    "Redirection with form.submit()",
    "",
    "Bot Fingerprinting with navigator.userAgent",
    "Bot Fingerprinting with navigator.platform",
    "Bot Fingerprinting with navigator.vendor",
    "Bot Fingerprinting with window.webdriver or navigator.webdriver",
    "Bot Fingerprinting with navigator.languages",
    "Bot Fingerprinting with navigator.plugins",
    "Bot Fingerprinting with navigator.mimeTypes",
    "Bot Fingerprinting with __phantomas, _phantom, __nightmare, __puppeteer",
    "Bot Fingerprinting with _selenium or _awesomium",
    "Bot Fingerprinting with mouse events: mousemove, mousedown, mouseup",
    "Bot Fingerprinting with pointer events: pointermove, pointerdown, pointerup",
    "",
    "VM Detection with CPU Count",
    "VM Detection with GPU Renderer",
    "VM Detection with Device Memory: navigator.deviceMemory",
    "VM Detection with Hardware Concurrency: navigator.hardwareConcurrency",
    "VM Detection with Screen Resolution: screen.width, screen.height",
    "VM Detection with Screen Color Depth: screen.colorDepth",
    "",
    "Uses Popups and Alerts",
    "Uses Button to Procceed",
    "Uses Random Time Delay to Render",
    "Uses Captchas",
    "Uses Randomized Content",
    "",
    "",
    "Cloaking with .htaccess",
    "Cloaking with PHP Code",
    "",
    "Uses Cookies",
    "Uses Referrer",
    "Uses User Agent",
    "",
    "Uses Request Repeatition Information",
    "Uses IP Information",
]
